export const products = [
  { id: 1, emoji: "💻", title: "Notebook HP i5 8va gen", price: "$380.000", location: "Palermo, Capital", distance: "3.2 km", bg: "#dbeafe", verified: true, category: "Electrónica", condition: "Usado" as const, description: "Notebook HP en excelente estado. 8GB RAM, SSD 256GB, pantalla 15.6\". Batería dura 4hs. Tiene algunos rayones mínimos en la tapa. Ideal para estudiantes o trabajo.", sellerId: 1 },
  { id: 2, emoji: "👟", title: "Zapatillas Nike Air 42", price: "$95.000", location: "Centro, Capital", distance: "1.1 km", bg: "#fce7f3", verified: true, category: "Ropa", condition: "Usado" as const, description: "Zapatillas Nike Air Max en talle 42. Usadas 3 veces, prácticamente nuevas. Color blanco con detalle negro. Vienen con caja original.", sellerId: 2 },
  { id: 3, emoji: "🛋️", title: "Sillón 3 cuerpos cuero", price: "$210.000", location: "Belgrano, Capital", distance: "5.8 km", bg: "#d1fae5", verified: false, category: "Hogar", condition: "Usado" as const, description: "Sillón de cuero marrón en buen estado. Algunas marcas de uso normales. Medidas: 2.20m de ancho. Retiro por Belgrano, no hacemos envíos por el tamaño.", sellerId: 3 },
  { id: 4, emoji: "🎨", title: "Kit pintura acrílica 24 colores", price: "$45.000", location: "Añatuya", distance: "180 km", bg: "#fef3c7", verified: true, category: "Arte", condition: "Nuevo" as const, description: "Kit completo de pinturas acrílicas marca Acrilex, 24 colores. Sin abrir. Lo compré para un proyecto que no llegué a hacer. Puedo enviar por encomienda.", sellerId: 1 },
  { id: 5, emoji: "📱", title: "iPhone 13 128GB libre", price: "$720.000", location: "Centro, Capital", distance: "0.8 km", bg: "#ede9fe", verified: true, category: "Electrónica", condition: "Usado" as const, description: "iPhone 13 color negro, 128GB, liberado para cualquier compañía. Batería al 91%. Con cargador y funda. No tiene golpes ni rayones.", sellerId: 2 },
  { id: 6, emoji: "🚲", title: "Bicicleta mountain bike rodado 29", price: "$185.000", location: "Villa Grimanesa", distance: "8.3 km", bg: "#e0f2fe", verified: false, category: "Deportes", condition: "Usado" as const, description: "Bicicleta MTB rodado 29, cambios Shimano 21 velocidades. Frenos a disco hidráulicos. Poco uso, en excelente estado. Lista para salir a rodar.", sellerId: 3 },
];

export const sellers = [
  {
    id: 1,
    name: "Marcos Ruiz",
    initials: "MR",
    memberSince: "marzo 2024",
    location: "Palermo, Capital",
    sales: 34,
    rating: 4.9,
    responseTime: "~20 min",
    phoneVerified: true,
    dniVerified: true,
    reviews: [
      { name: "Ana González", rating: 5, text: "Excelente vendedor, muy puntual y el producto era exactamente como lo describió." },
      { name: "Pablo Díaz", rating: 5, text: "Muy buena experiencia, respondió rápido y el envío llegó el mismo día." },
      { name: "Lucía Moreno", rating: 4, text: "Todo bien, demoró un poco en responder pero cumplió con todo lo acordado." },
    ],
  },
  {
    id: 2,
    name: "Sofía Castro",
    initials: "SC",
    memberSince: "enero 2024",
    location: "Centro, Capital",
    sales: 18,
    rating: 4.7,
    responseTime: "~1 hora",
    phoneVerified: true,
    dniVerified: false,
    reviews: [
      { name: "Tomás Pérez", rating: 5, text: "Todo perfecto, muy buena atención y producto como nuevo." },
      { name: "Valeria Ibáñez", rating: 4, text: "Bien en general, el producto llegó en condiciones." },
    ],
  },
  {
    id: 3,
    name: "Diego Mamani",
    initials: "DM",
    memberSince: "junio 2023",
    location: "Belgrano, Capital",
    sales: 52,
    rating: 4.8,
    responseTime: "~30 min",
    phoneVerified: true,
    dniVerified: true,
    reviews: [
      { name: "Carmen López", rating: 5, text: "Vendedor muy confiable, ya le compré dos veces. Recomendado." },
      { name: "Rodrigo Silva", rating: 5, text: "Producto en excelente estado, trato impecable." },
      { name: "Marina Torres", rating: 4, text: "Buena experiencia, coordinamos rápido el punto de encuentro." },
    ],
  },
];

export const categories = [
  "Todos",
  "Electrónica",
  "Ropa",
  "Hogar",
  "Deportes",
  "Vehículos",
  "Herramientas",
  "Juguetes",
  "Libros",
  "Mascotas",
  "Bebés",
  "Jardín",
  "Arte",
];
